#!/bin/bash
-rwxr--r-- 1 root root 32 Jul 10 05:32 0-hello_world
-rwxr--r-- 1 root root 48 Jul 10 07:06 10-no_more_js
-rwxr--r-- 1 root root 48 Jul 10 07:41 11-directories
-rwxr--r-- 1 root root 25 Jul 10 07:46 12-newest_files
-rwxr--r-- 1 root root 27 Jul 10 07:52 13-unique
-rwxr--r-- 1 root root 36 Jul 10 08:01 14-findthatword
-rwxr--r-- 1 root root 43 Jul 10 08:10 15-countthatword
-rwxr--r-- 1 root root 41 Jul 10 08:13 16-whatsnext
-rwxr--r-- 1 root root 46 Jul 10 08:17 17-hidethisword
-rwxr--r-- 1 root root 53 Jul 10 08:31 18-letteronly
-rwxr--r-- 1 root root 22 Jul 10 08:36 19-AZ
-rwxr--r-- 1 root root 38 Jul 10 06:02 1-confused_smiley
-rwxr--r-- 1 root root 23 Jul 10 08:38 20-hiago
-rwxr--r-- 1 root root 16 Jul 10 08:40 21-reverse
-rwxr--r-- 1 root root 28 Jul 10 06:05 2-hellofile
-rwxr--r-- 1 root root 39 Jul 10 06:08 3-twofiles
-rwxr--r-- 1 root root 29 Jul 10 06:11 4-lastlines
-rwxr--r-- 1 root root 29 Jul 10 06:14 5-firstlines
-rwxr--r-- 1 root root 36 Jul 10 06:26 6-third_line
-rwxr--r-- 1 root root 98 Jul 10 06:51 7-file
-rwxr--r-- 1 root root 36 Jul 10 06:56 8-cwd_state
-rwxr--r-- 1 root root 39 Jul 10 07:00 9-duplicate_last_line
-rw-r--r-- 1 root root 21 Jul 10 05:21 README.md


